### ISSUE TITLE
fakeMessages in MessageHistory all have the same timestamp 

### ISSUE THREAD

**Issue by KimWu888** [skychatorg/skychat#89]
Yesterday a new member joined our chatroom and was able to guess that the message history displayed was faked, due to all the timestamp being the same. Has this issue ever been addressed, or is this behavior expected ? 

Else I was thinking we could also fake the timestamp, the challenge being that after a page refresh the messages should keep the same timestamps. This implies that we cannot rely on the current timestamp or any randomization, since the algorithm has to be deterministic.

This determinism couldn't have been achieved if the chat displayed the full date, but we are day-agnostic so any time displayed can be credible whatever the current time is. 

We can achieve this "fool-proof" time setting by computing a hash based on some heuristics (username, number of chars posted originally, real timestamp...). This hash could then be understood as the "time elapsed since the previous message". Starting from midnight, we could keep summing each of the timestamps to offer a credible "fake timestamping" to our visitors.

What do you think?

**Comment by 7PH** [comment]
> all the timestamp being the same. Has this issue ever been addressed, or is this behavior expected ?

No, this is not the expected behavior. Ideally, fake messages history should be deterministic.

> Else I was thinking we could also fake the timestamp

Each fake message corresponds to a real message which has been posted in the room earlier, so I actually do not think this is necessary. Each fake message timestamp should be the same than the timestamp of the real message it refers to. The user is already re-used for these reconstructed fake messages, but not the timestamp. So, while your proposition would be fun to implement, there is an easier way to implement this which is to just re-use the timestamp of the real message.

So I think this highlights two issues causing the fake messages history to be non-deterministic:
- There is a bug causing the timestamps not to be re-used when creating the fake version of the messages
- In the same spirit, we can do the same for the message content. Meaning that multiple page reloads from a guest user would always display the same faked messages, with the same users, timestamps and content.

Thanks for pointing that out. I just made the changes to make the fake message timestamps and content deterministic.
